apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-springboot
  labels:
    app: backend-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-springboot
  template:
    metadata:
      labels:
        app: backend-springboot
    spec:
      containers:
        - name: backend-springboot
          image: backend-springboot:v0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          ports:
            - containerPort: 8080
