apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-springboot
  labels:
    app: backend-springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-springboot
  template:
    metadata:
      labels:
        app: backend-springboot
    spec:
      containers:
        - name: backend-springboot
          image: backend-springboot:v0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /items/hostname
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /items
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
