version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: items-postgres
    # 12 factor external configuration via environment variables
    environment:
      POSTGRES_DB: itemsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  springboot:
    # build: ./backend-springboot
    image: backend-springboot:v0.1
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/itemsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: yourpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  flask:
    # build: ./frontend-flask
    image: frontend-flask:v0.1
    container_name: flask-client
    ports:
      - "5123:5123"
    depends_on:
      - springboot

volumes:
  pgdata:
